-- Query: Revenue per Campaign
-- Business question: What is the actual revenue generated by each campaign?
-- Key metric: total_revenue
-- Insight: Email campaigns generated highest revenue despite lowest budgets —
--          Telemarketing generated lowest ROI despite highest spend



SELECT
    c.campaign_id,
    c.campaign_type,
    c.budget,
    COUNT(DISTINCT t.transaction_id)         AS total_transactions,
    ROUND(SUM(t.amount), 2)                  AS total_revenue,
    ROUND(AVG(t.amount), 2)                  AS avg_transaction_value
FROM campaigns c
LEFT JOIN campaign_responses cr 
    ON c.campaign_id = cr.campaign_id
LEFT JOIN transactions t 
    ON cr.customer_id = t.customer_id
    AND cr.conversion = 1
GROUP BY c.campaign_id, c.campaign_type, c.budget
ORDER BY total_revenue DESC;
